### ISSUE TITLE
Check it out

### ISSUE THREAD

**Issue by justbur** [justbur/emacs-which-key#1]
@syl20bnr I decided to neglect my work today and start on this. I put together a minimal working rewrite of guide-key. It's very basic, but it doesn't use a polling function anymore (just `run-with-idle-timer`) and it includes some variables for replacement lists. I hard-coded some stuff to just to get started.

I haven't figured out window-purpose yet, so I'm still using popwin, but I think you'll see that the code is pretty simple all things considered. 

I'd like your feedback on this (and guidance if possible), since I've never written an emacs package before.

**Comment by syl20bnr** [comment]
This is really exciting :+1: 
I would suggest to use alist based on the key sequence as much as possible in order to be decoupled from emacs internal, that is:
- alist for command names like `("SPC f f" . "find files")`
- alist for prefix commands like `("SPC f" . "files")`
- alist for major mode working for both command names and prefixes like
  - `("SPC m d" . (emacs-lisp-mode "debug"))`
  - `("SPC m d m" . (emacs-lisp-mode "expand macro"))`

**Comment by justbur** [comment]
Thanks!

I'm not sure I understand your suggestion about using alists. Which step are you referring to?

I switched to using the mini buffer last night and the more I think about it the more sense it makes to me because it matches how I would expect this to behave. I want to include the option to use other methods but I like it so much I want to make it default until I find something better. It also saves one line of screen space :-). 

I also had the idea of breaking the list of bindings into "pages" and then flip through them after short delays while waiting for the next key press. That way it's easier to deal with tall buffers.

**Comment by syl20bnr** [comment]
My remark was about making all the information alist driven in some
way instead of inferring some of them from emacs. This way we get full
control about what we display in the minibuffer. But inferring from emacs
and have which-key working automatically like guide-key is what people not
using Spacemacs will want...
So making it magically working like guide-key plus the possibility to
override anything via alists may be the way to go, maybe this is what you
started to do in which case it will fit exactly what I need at Spacemacs
level (getting full control of what will be displayed in the buffer).

I like the idea to use the minibuffer, you are right that it makes sense to
use it. The only limitation I see is that you won't have the choice to
display it vertically but as far as I'm concerned it is not an issue.

For the automatic switch it is tricky because it will surprise some users
but on the other end there is not a lot of possibilities to handle this.
Some random thought about this:
- we could mitigate the issue by sorting the bindings by usage frequency or
by "most recently used" but it is not a solution
- if there is not enough room then we could take the whole screen
- use the scroll wheel ? May require some black magic
- in the same spirit of we can make it work with scroll-wheel then there is
no reason we could not make it work with keys like arrow keys, it has the
disadvantage of making SPC arrow-key impossible but in the case of
Spademacs this combination does not exist. So if it is configurable the
user can find some holes ?
- we think out of the box and come with a brand new way of dealing with
progressive discovering of keys, I think about some kind of selection or
behavior a la magit-popup or crazier. This solution must resolve the
following issue: be able to use some keys for which-key without perturbing
the key sequence that the user want to input. I make me think that with a
smartly choosen set of keys that overlap each other for next/previous keys
we could always have one available that would not prevent the user to reach
her targeted sequence. For instance we can have a set of possible
candidates for next-page and we look which one can be used safely given the
current set of proposed keys then we display a short docstring in the
minibuffer with the key we selected as safe to change page.


Le samedi 4 juillet 2015, Justin Burkett <notifications@github.com> a
écrit :

> Thanks!
>
> I'm not sure I understand your suggestion about using alists. Which step
> are you referring to?
>
> I switched to using the mini buffer last night and the more I think about
> it the more sense it makes to me because it matches how I would expect this
> to behave. I want to include the option to use other methods but I like it
> so much I want to make it default until I find something better. It also
> saves one line of screen space :-).
>
> I also had the idea of breaking the list of bindings into "pages" and then
> flip through them after short delays while waiting for the next key press.
> That way it's easier to deal with tall buffers.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/justbur/emacs-which-key/issues/1#issuecomment-118499465>
> .
>


-- 
-syl20bnr-

**Comment by justbur** [comment]
I understand what you mean about the alists now. My goal now is to give the necessary options to condense the information as each user or startup package ;-) sees fit. I even had some crazy ideas like being able to condense the window selection functions in spacemacs into "[N] -> Select Window [N]" (or something like that) using an alist with regexp enabled.

I agree that the paging stuff might be awkward if not done correctly. I built in some basic paging logic, but am just displaying the first page at the moment if that's all that fits. I was thinking about playing with automatically scaling text if the bindings don't fit, but still the best approach I think is to get the information condensed and useful. I'll keep thinking about it. 

I'm not crazy about the usage frequency thing for two reasons. One is it would (I think) add a lot of complexity to the code, because I'd have to build in a way to collect and analyze choices (haven't looked into packages for this). The second is I'm not sure you are looking for your most used key binding when you look at which-key/guide-key. You might be looking for something you don't use or have never used. I don't know if there is a good way to predict what people are looking for (at least in a simple package). 

The vertical buffer option will be there. I just think minibuffer is the best default at the moment. Of course, I'm also going to make it extensible. You'll be able to write your own show-buffer function to put it anywhere :-)

**Comment by justbur** [comment]
@syl20bnr We now have the (horribly named) alist `which-key-key-based-description-replacement-alist` which can include elements of the form `("SPC f f" "find files")` or `("SPC m d" "debug" emacs-lisp-mode)`. The first applies everywhere. The second applies just when in `emacs-lisp-mode`. Let me know if this is adequate for spacemacs. I can put a helper function in there to easily add a lot of bindings. 

These simply overwrite the description for those keybindings.

**Comment by syl20bnr** [comment]
This seems perfect :+1:

**Comment by justbur** [comment]
Great :-)
