### ISSUE TITLE
Strange hiding behavior in OS X GUI Emacs

### ISSUE THREAD

**Issue by jasonm23** [justbur/emacs-which-key#123]
Only tested/found with Emacs Mac Port (aka Railwaycat emacs mac)

1. Which key flashes up the guide momentarily...
2. Guide disappears.
3. Switch app focus to something else
4. Refocus Emacs, interact with pointer... 
5. now the guide reappears...?!?

Tested In terminal... it's fine.

![which-key-bug](https://cloud.githubusercontent.com/assets/71587/15199928/f964d508-1814-11e6-9016-d0ae81cc2b1f.gif)

**Comment by justbur** [comment]
Are you using the minibuffer for the display area? 

What are the values of `which-key-idle-delay` and `echo-keystrokes`?

**Comment by jasonm23** [comment]
Yes, minibuffer display.

My which-key config : 

https://github.com/ocodo/.emacs.d/blob/master/_configs/use-which-key.el

**Comment by jasonm23** [comment]
No settings for echo-keystrokes (outside of a let, e.g. used by other packages, evil and wanderlust as let overrides.)

Which-key-idle-delay is not set anywhere, remains as default.

**Comment by justbur** [comment]
Can you check the value of `echo-keystrokes`? It appears that it's firing after you switch frames, which is killing all of the information in the minibuffer. 

BTW, I find `which-key-setup-side-window-bottom` to be almost equivalent to the minibuffer but much more reliable. The minibuffer display also doesn't work as smoothly with the paging functions. You can still display the page information on the left if you like with `(setq which-key-show-prefix 'left)` if you like.

**Comment by justbur** [comment]
I think what's happening is 

popup shows => echo keystrokes wipes minibuffer (if it's longer than `which-key-idle-delay`) => unfocus => refocus (which-key timer restarts and overrides echo-keystrokes)

The timer restarting on focus is a feature to prevent it from running when emacs is in the background. It looks weird in your case because the echo keystrokes comes in. If you set it to something shorter than `which-key-idle-delay` it "shouldn't" be a problem.

**Comment by jasonm23** [comment]
What you're saying is a little confusing, the default value of `echo-keystrokes` is 1 on an unconfigured Emacs.

Which-key has a specific variable (`which-key--echo-keystrokes-backup`) for backing up the original value, isn't that used to deal with this issue?

I should also make a note here that I've been using which-key for 10 months, and never had this problem until the last update.

**Comment by jasonm23** [comment]
I can add `(setq echo-keystrokes 0)` to my config of course, and `which-key-setup-side-window-bottom` might be ok.

I'm wondering why the problem has only just surfaced though.

**Comment by jasonm23** [comment]
I'll do some more investigation, starting with rollback the version back to my last update.

**Comment by justbur** [comment]
Ok, it's strange that it manifests itself like this, but I understand what happened now. I changed the default of `which-key-echo-keystrokes` recently to a value that is calculated at load instead of the default of 0 which is what it was before. The calculation missed the case where `echo-keystrokes` was equal to `which-key-idle-delay`, which was a silly mistake. It should be fixed in the next update.

**Comment by jasonm23** [comment]
Thanks, Nice catch!

**Comment by justbur** [comment]
If you have a chance to check this issue, the new version of which-key is on melpa. Hopefully it's fixed for you.

**Comment by jasonm23** [comment]
Thank you I'll check it out today

**Comment by jasonm23** [comment]
Fixed by 796d0ccefbf8f4c07bf23dff621da56cbbf4ac89
