### ISSUE TITLE
New Features?

### ISSUE THREAD

**Issue by justbur** [justbur/emacs-which-key#14]
@bmag Is there any feature or change you are thinking about adding? I'm just curious, because I don't have a lot more in mind. 

I'm really happy with the minibuffer option, which has been great for me. I want to play with the alists some more and see what makes sense for defaults. I also want to figure out the best way to show more keybindings (I'm thinking of `C-x` mainly), maybe with #8 and playing with text scaling or paging or something like that. Once this stabilizes, I'll write up some documentation and try to put it on MELPA.

Also, how's the performance for you? Any slowdown on your machine? guide-key was causing problems for people with constant wake-ups, and that was part of the motivation for the rewrite.

**Comment by bmag** [comment]
I don't have any new features in mind, but I there are some fixes and refinements that should be done, as you can see in the new issues I have opened.

As for how to show more keybindings, both the text scaling and the paging are valid options. In case of text scaling, it would probably require changes in calculating the dimensions of the window. Those changes could be non-trivial, but I'm willing to try it once we improve and fix some other issues. In case of the paging, we would need a user-friendly method of changing pages - a timer with a reasonable delay, a special key, or something else. Anyway, I think maybe we should let the code mature a bit before tackling this particular issue.

As for performance, I didn't notice any slowdown with guide-key, though it could be that I had slowdowns but didn't know the cause was guide-key. A problem I did have with guide-key, and some others as well, is that guide-key sometimes doesn't show all of the available keys. Currently, which-key also suffers a similar problem

**Comment by justbur** [comment]
Coming up with a reasonable way of showing all the keys is on my wish list too, but I think you're right about getting the code to a state where one page can be shown reliably first.

**Comment by syl20bnr** [comment]
For the paging navigation I like the idea of having a list of key pairs containing:
- `<` and `>`
- `left` and `right`
- `up` and `down`
- `n` and `p`
- `[` and `]`
- etc...

Then we choose the first available pair given the current set of key bindings, if don't find anything then we have a fallback on the less intrusive solution (ie. the last pair in the list, the first being the most natural pair to navigate). Since the pair may change given the set we have to explicitly display a docstring somewhere showing the active keys for page navigation.

In the case where we need to override keys belonging to the set we'll have to do some black magic to intercept the pressed key and continue the key sequence. But I think that in a first implementation we can avoid this case by having enough pair diversity to handle a large number of different sets.

**Comment by justbur** [comment]
There should never really be more than a handful of pages. I was just thinking about binding one key like an f key to cycle through. I'm not sure I like that the key binding is dependent on the keys in the buffer which is dependent on the mode and the state in evil at least.

**Comment by syl20bnr** [comment]
If only `f` is used then `SPC f` cannot be entered. The key to navigate the pages should not prevent any combination from working.

**Comment by justbur** [comment]
Sorry I meant a function key like f6. I understand the need to avoid
existing bindings

**Comment by justbur** [comment]
Although I guess the only difference with a regular binding is that it
would apply to every sub binding (or whatever the right way to say that is)
kind of like C-g

**Comment by justbur** [comment]
I think something like C-TAB might work. Sorry for the sequence of emails.
I tend to get ideas after I press send.

**Comment by kaushalmodi** [comment]
Would it be possible to use dynamic key bindings to navigate the pages?

`which-key` should be able to use any of the keys from `F1` to `F12`. But based on the availability of that binding in the keymap that `which-key` is currently showing, the first key available of that 12 keys is used automatically. So that the use is not confused, `which-key` can display the exact key to be pressed to change the pages.

Let's say I have `C-x <f1>` bound to something but `C-x <f2>` is not bound to anything. Then when `which-key` displays the map for `C-x`, it displays something like `Press f2 to change page.`.

On the other hand, let's say I do not have `C-c <f1>` bound to anything. Then when `which-key` displays the map for `C-c`, it displays something like `Press f1 to change page.`.

*Just an idea.. I do not know how to implement this.*

**Comment by justbur** [comment]
I played around with this sort of thing a few days ago. It seems tricky though (even for a set change page key), because right now the code is just listening to the key sequences and not interacting with them. I think to add key bindings I would need to intercept incomplete key sequences, execute a command to change the page, then restore the old incomplete key sequence by faking it (or something to that effect). One of the issues was I wasn't able to change the keymap on the fly in a way that affects the current key-sequence (it wasn't picking up the change). 

I could try to add a keybinding to every keymap ahead of time, but that's tricky too because I'd have to worry about keymaps being introduced and changed.

**Comment by justbur** [comment]
Closed in favor of starting newer focus threads
