### ISSUE TITLE
Multiple replacements, same binding

### ISSUE THREAD

**Issue by Kungsgeten** [justbur/emacs-which-key#156]
Hi!

How would I replace multiple strings in the same description? I had an older version (before `which-key-replacement-alist` I think) where it  worked. Now I'm doing this:
```
  (mapc
   (lambda (x)
     (push `((nil . ,(car x)) . (nil . ,(cdr x))) which-key-replacement-alist))
   '(("kill" . "☠")
     ("projectile" . "✎")
     ("helm" . "⎈")
     ("other-window" . "↗▯")
     ("other-frame" . "↗⌧")))
```
And would expect the description to be `⎈-✎-find-file`, but only the first match seems to be replaced (I get `⎈-projectile-find-file`).

**Comment by justbur** [comment]
Hi, 

For the moment you will have to specify your replacements so that one match is enough. This should work for example

```elisp
(mapc
   (lambda (x)
     (push `((nil . ,(car x)) . (nil . ,(cdr x))) which-key-replacement-alist))
   '(("kill" . "☠")
     ("helm-projectile" . "⎈-✎")
     ("^projectile" . "✎")
     ("helm" . "⎈")
     ("other-window" . "↗▯")
     ("other-frame" . "↗⌧")))
```

I understand that's less convenient, but the changes that went into `which-key-replacement-alist` were made to reduce the complexity of the logic, consolidate the replacement facility into one list, and open up the possibility of making a replacement on the basis of both the key and the binding description (this wasn't possible before). I will think about making it a little more flexible, but baring any obvious downsides I'm leaning towards leaving it as it is.

**Comment by Kungsgeten** [comment]
I think its a good idea to have it all in one list. Would there be problems if all matches were replaced, instead of just the first one?

**Comment by justbur** [comment]
No, not really. I just had to rework a couple of things. 

I thought multiple replacements could get confusing and might be unexpected. I also was slightly concerned about performance. 

In any case, you now have the option to bring the behavior back with 

```elisp
(setq which-key-allow-multiple-replacements t)
```

Your original example should work with that setting.

**Comment by Kungsgeten** [comment]
Thanks! I'll try it out!
