### ISSUE TITLE
Can I use after-init-hook on which-key?

### ISSUE THREAD

**Issue by ReimuXMX** [justbur/emacs-which-key#184]
Hello, and sorry for my poor English.

I want to slightly increase the loading speed, can I write like this?
```emacs-lisp
(require 'which-key)
(add-hook 'after-init-hook
          (lambda ()
            (which-key-mode)
            (diminish 'which-key-mode)
            (which-key-setup-side-window-bottom)))
```

OR

```emacs-lisp
(require 'which-key)
(add-hook 'after-init-hook 'which-key-mode)
(with-eval-after-load 'which-key
  (diminish 'which-key-mode)
  (which-key-setup-side-window-bottom))
```

Thanks.

**Comment by justbur** [comment]
The second is better but will not improve load speed. You can get equivalent behavior by using the second option and eliminating the require step. It’s unnecessary because `which-key-mode` will auto load the library.

**Comment by ReimuXMX** [comment]
Thanks.

**Comment by justbur** [comment]
yes, exactly

**Comment by ReimuXMX** [comment]
Thank you very much!

**Comment by ReimuXMX** [comment]
Is this not useful to improve the loading speed?

Because after my test, it is not fast milliseconds than load it directly...

**Comment by justbur** [comment]
It depends a little on how you measure it, but no this should not have a noticeable effect on loading time. The issue is that as soon as you call `which-key-mode` the whole package needs to be loaded anyway. So it's a matter of loading it manually with `require` or waiting for the autoload mechanism to do it. 

In any case, this certainly has nothing to do with how which-key works.

**Comment by ReimuXMX** [comment]
thank you for the explanation
I will close this issue.
