### ISSUE TITLE
BUG: which-key window not wide enough

### ISSUE THREAD

**Issue by bmag** [justbur/emacs-which-key#19]
Using these settings:
```elisp
(setq which-key-popup-type 'side-window
      which-key-side-window-location 'right
      which-key-side-window-max-width 90)
```
Results in a which-key window that isn't wide enough for the lines in the which-key buffer. The "empty" lines contain spaces, and each such line is actually the continuation of the previous line (Spacemacs makes it look like two different lines, but in the buffer it's a single line).
![which-key-not-wide-enough](https://cloud.githubusercontent.com/assets/4334375/8564647/bd8e5ab0-2556-11e5-9138-4bf2c3d41c8d.png)

This is the actual content of the which-key buffer. Notice the cursor is at the bottom left corner of the text:
![which-key-actual-buffer](https://cloud.githubusercontent.com/assets/4334375/8564744/acc92c54-2557-11e5-96d2-14287dccf657.png)

I will debug this later, but I suspect we may have a slight miscommunication about `which-key/show-popup` and `which-key/popup-max-dimensions`. As I understand it, the ACT-POPUP-DIM argument to `show-popup` specifies the width and the height of the popup window as follows:
- width: the length of each line in which-key buffer, or the length of the longest line in which-key buffer. Length is the same as "number of columns". `show-popup` should take care of calculating necessary width to accommodate for fringes, margins, scroll bars, etc.
- height: the number of lines in which-key buffer.

Assuming all lines are of the same length, ACT-POPUP-DIM should be equivalent to:
```elisp
(with-current-buffer which-key-buffer-name
  (save-excursion
    (goto-char (point-max))
    (cons (line-number-at-pos) (current-column))))
```

Concerning `popup-max-dimensions`, as I understand it, the function should return the maximal height and width that `show-popup` can handle. So the following should always be true:
```elisp
(and (<= (car argument-to-show-popup) (car popup-max-dimensions-return-value))
     (<= (cdr argument-to-show-popup) (car popup-max-dimensions-return-value)))
```

Please share what meaning you meant those parameters to have, so we can agree on a single meaning and fix this issue.

**Comment by justbur** [comment]
I think it's something that should be fixed in the show-buffer-side-window function. width is the number of columns of each line (except the prefix line if that is shown on top). I'm padding each key-description to a uniform length, so the number of characters in each column should be exactly the same. `column-width` is the width of each padded key-description pair. `act-width` is calculated as
```
         (n-columns (/ max-width column-width)) ;; integer division
         (act-width (* n-columns column-width))
```

height is the number of lines 

```
          (setq pages (reverse pages)
                first-page (concat prefix-string (car pages))
                act-height (1+ (s-count-matches "\n" first-page)))
```

Yes, I think that calculation would be equivalent for `act-popup-dim`. Also, that second condition should be true. 

I need to leave soon, but my guess is that height and width for display-buffer mean something different from what the code currently assumes. Could be the fringe, scroll bar, etc. like you suggest. This correction should go in the corresponding show-popup function to keep the above definitions consistent. 

Thanks

**Comment by justbur** [comment]
Or it could just as well be handled in the max dimensions function. Whichever is easier.

**Comment by justbur** [comment]
So that was kind of a hack. I call `fit-window-to-buffer` after displaying the buffer. I don't think it's bad though. We still get really close on the dimensions using the max-dimensions functions, and then this final call just adjusts it a little to make everything fit. I guess it could be bad if someone had their max width set precisely to a very specific number.

What do you think?

**Comment by justbur** [comment]
@bmag Was this a reasonable solution for you?

**Comment by bmag** [comment]
I'm actually writing a comment right now :-)

**Comment by bmag** [comment]
Haven't tried it yet, but I agree that this is an easy solution, and the first implementation of the frame case used the similar `fit-window-to-frame` function, but I see two problems:
- resizing the window may cause it to become bigger than the user defined max size. This can be fixed easily by passing some parameters to `fit-window-to-buffer`.
- using `fit-window-to-buffer` means that we display the window, then resize it. It could cause the window to flicker when created, since there is a small delay after `display-buffer` and before `fit-window-to-buffer` is executed. If that delay is long enough for the eye to catch it, then it would look like a flicker. I suspect it would be noticeable for some users. I know that it was noticeable in the frame case, but frames take longer to draw than windows.

I'll try to improve during the weekend.

**Comment by bmag** [comment]
About the `act-width`, it would be easier for `which-key/show-popup` if that width included the prefix. This is because when showing the popup window, the window needs to be wide enough to show all the lines in the buffer without truncating them - and that includes the prefix. So I would prefer if `act-width` would be:
```elisp
;; prefix-width here means the width of the prefix plus any spaces between it and the first column
;; didn't look in the code to see what are the real variable names
(+ (* n-columns column-width) prefix-width)
```
Would that be possible?

The other solution is to ignore ACT-POPUP-DIM in `which-key/show-popup`, and instead use the code I pasted above (pasted here again, for convenience):
```elisp
(with-current-buffer which-key-buffer-name
  (save-excursion
    (goto-char (point-max))
    (cons (line-number-at-pos) (current-column))))
```
Which is also OK, but I prefer to avoid it if we can.

**Comment by justbur** [comment]
You're right. I fixed `act-width` in 3c5f1ba. It should include the prefix length.

**Comment by justbur** [comment]
Hm. I'm not sure about the flickering. I didn't notice any with side-window. 

So technically, it's not bigger than the user-specified size. Assuming my calculations are correct the text width maxes out at the user-specified size and the correction is to get the window to display all of that text. `window-width` is probably specifying the whole window width including fringe and all of that. It would be nice if you could specify `window-text-width` but I don't see that option. 

Maybe we leave it for the side-window case, and do something fancier for the frame. I'm not convinced the frame is that useful, but I'm happy to leave it in there. Maybe you have a good use case?

Instead of a frame, a tooltip might work better, like pos-tip? I don't know anything about using those though.

**Comment by bmag** [comment]
`window-width` specifies only the width of the text area. `window-total-width` includes the fringe and all that. Same for `window-height` and `window-total-height`. The only functions that should care about the fringe and other display component should be `which-key/side-window-max-dimensions`, `which-key/frame-max-dimensions`, `which-key/show-buffer-side-window` and `which-key/show-buffer-frame`.

There are emacs users that prefer each window to be displayed in its own frame. Some also use advanced/customizable window manager (e.g. [Awesome](http://awesome.naquadah.org/)), though I have never tried them. I believe those users might benefit from the frame case.

I don't have much experience programming tooltips, but that could be an additional case. You could look at [guide-key-tip](https://github.com/aki2o/guide-key-tip) for reference.

**Comment by justbur** [comment]
I occasionally use tiling window managers, and I guess you might want a dedicated frame in that case.

Then something is wrong then, whether it's the sizing of the window or my calculations, because it should be spitting out the right number for the width now.

**Comment by justbur** [comment]
I was curious, so I did some tests. In your example, `act-popup-dim` asks for a width of 77 when I hit `C-x`, but `window-text-width` reports 74 before the fit to buffer call. No idea why, but that explains the result.

**Comment by bmag** [comment]
`which-key/show-buffer-side-window` creates the window with an initial total-width of 77, instead of a text-width of 77. The total-width should be bigger, to include possible fringes and scroll bar. I will fix it probably tomorrow.

By the way, isn't `which-key-side-window-max-width` set by default to 60? Why does which-key produce a buffer wider than 60? Or did you set it the max width to something else?

**Comment by justbur** [comment]
Thanks

Those defaults don't mean anything. I haven't put any thought into what the
default should be for max width and height. I'm now thinking it should be a
percentage.

**Comment by bmag** [comment]
What's bothering me is that it looks like the window is bigger than what the user wants it to be. If the user defines a max width, why is the window wider than it?

**Comment by justbur** [comment]
I completely agree. I guess there are two options, either say that the user-specified value is setting the text width (putting the burden on them to account for fringes and the like if they care) or fix the problem in the max-dimensions logic so that populate-buffer has the correct dimensions to work with.

**Comment by bmag** [comment]
I just realized that which-key uses some unicode characters that have *a different width* than the regular ascii characters. Specifically, the arrows are displayed wider than the ascii characters, resulting in a window that isn't wide enough.  
So we either need to use pixel-wise calculations, or use `fit-window-to-buffer`, or simply create a window that is a little wider than necessary. I'll experiment with it.

**Comment by justbur** [comment]
Oh, I suppose the arrows could be wider. I just tested again setting `(setq which-key-separator ">")` though and the width is still not correct for the side window in #23.

**Comment by bmag** [comment]
Really? So let's just go with `fit-window-to-buffer` and be done with it...

**Comment by justbur** [comment]
Ok, fine with me. Do you want to rework #23 then? It should still be useful no?

The unicode explanation doesn't make complete sense, because the window size was off by 3 characters for me which seems like too much for just one or two slightly wider characters.

**Comment by bmag** [comment]
See https://github.com/justbur/emacs-which-key/pull/23#issuecomment-120050209
