### ISSUE TITLE
How to modify the config to silent the user warning?

### ISSUE THREAD

**Issue by et2010** [justbur/emacs-which-key#310]
The recent update of which key leads to user warning at startup of the spacemacs. I found it's caused by those configurations:

https://github.com/syl20bnr/spacemacs/blob/443311c8f1d7c6ebbe1d10be576a4edc47e03a5a/layers/%2Bsource-control/git/packages.el#L275

I'm not sure what those lines were supposed to do and how to modify those lines without breaking spacemacs. Can you recommend a fix for the above lines in order to silent the warning? Thank you in advance!

@justbur

**Comment by justbur** [comment]
That's an incorrect usage of that function. It will need to be fixed in spacemacs

**Comment by duianto** [comment]
A PR is pending that reverts the incorrect usage.
Revert "Fix which-key entries: gr and gs in dired and magit"
https://github.com/syl20bnr/spacemacs/pull/14869

A recent which-key update seems to have made that fix obsolete.
The correct which-key entries still appear as expected when the fix is reverted.

**Comment by et2010** [comment]
Thank you! After updating spacemacs, the issue was gone!
