### ISSUE TITLE
Width estimate broken for some fonts

### ISSUE THREAD

**Issue by elemakil** [justbur/emacs-which-key#79]
When using the non-standard font for spacemacs -- in my case that is [Inconsolata LGC](https://github.com/DeLaGuardo/Inconsolata-LGC) -- the width estimate for the `which-key` popup window is wrong. See this example screenshot:

![Example Screenshot](http://ibin.co/2L4EgiZGCpfw)

I'm running Mac OS Yosemite with [railwaycat's](https://github.com/railwaycat/emacs-mac-port) `emacs-mac-port` in GUI mode. My spacemacs config (for `which-key`) is the default.

~~Reverting to the default font (`Source Code Pro`) solves the problem.~~  

**Edit:** Seems I was too quick when saying this solves the problem. The problem is fixed for the <kbd>Ctrl</kbd> + <kbd>x</kbd> and <kbd>Ctrl</kbd> + <kbd>c</kbd> `which-key` buffers (and possible others). However, for <kbd>Space</kbd> the problem persists. I think this problem **can not be fixed by simply changing the font**.

**Comment by justbur** [comment]
Can you try the standard version of inconsolata?

**Comment by elemakil** [comment]
The choice of font seems only partially responsible. Using the official `Inconsolata` _"fixes"_ the problem for the <kbd>space</kbd> buffer. 

**But** the problem exists for `Source Code Pro` at 12 pt size and disappears for the same font at 11pt size. My guess is that the problem is independent of the font.

**Comment by justbur** [comment]
Ok I'll see if I can reproduce it. Haven't been able to yet, but I also
don't have a lot of time at the moment. Maybe @bmag has an idea.

I know this can happen with Unicode characters because they can be wider
than the ascii characters and that throws the calculation.

But what's odd about the picture is the word wrap. I explicitly turn on
line truncation in the which key buffer.

The other thing that might be happening is that the function that reports
the available width is giving incorrect answers.

**Comment by bmag** [comment]
Hey :smile:

I wasn't able to reproduce the bug, though I tried several fonts, font sizes and frame sizes.

I've only ever seen those squiggly arrows (in the beginning of truncated line continuations) when `toggle-truncate-lines` is disabled, so I suspect something is wrong with the line truncation. I don't know if the problem is a bug in which-key or something in @elemakil's config.

Unfortunately I don't have much time either these days, but @elemakil I suggest you check if somehow your config disables `toggle-truncate-lines` globally or something of that sort. I'll try to find time before Sunday to come up with a way to debug this (unless you solve it beforehand of course).

**Comment by justbur** [comment]
Thanks @bmag. The line truncation is wrong and the width of the line is much too long. I'll try again to reproduce when I get a chance.

**Comment by elemakil** [comment]
@justbur your analysis was spot on, the offender is
```
(global-visual-line-mode)
```
which I put into my config on purpose because I normally want it turned on **everywhere**...if you rely on line truncation for `which-config` to work properly that is unfortunate. I didn't even think that this might be related.

I'd suggest adding a check that explicitly disables `visual-line-mode` in the `which-key` buffer. I.e. inserting
```
(when visual-line-mode
    (visual-line-mode nil))
```
somewhere between L 405 and 415 in `which-key.el`. I assume, that the _buffer_ that is used for showing the keys is killed upon exit, so there's no need to restore `visual-line-mode`.

**Comment by justbur** [comment]
Thanks for making me aware of that. I'll look into controlling for that
option.

**Comment by justbur** [comment]
This issue was a combination of two problems. (1) The visual line mode thing you mentioned, which I think I have prevented now. (2) The unicode correction was not working. Unicode characters are sometimes wider than ascii characters and this throws the calculation. I have a correction term in there to give some leeway for this but it was not working correctly. You can also increase the correction if you run into problems for certain fonts.
